stream-fusion:
    image: ghcr.io/beluchon/stream-fusion:latest
    container_name: stream-fusion
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      - SECRET_API_KEY=
      - TMDB_API_KEY=
      - YGG_PASSKEY=
      - SHAREWOOD_PASSKEY=
      - REDIS_HOST=stremio-redis
      - PG_HOST=stremio-postgres
      - PG_USER=stremio
      - PG_PASS=stremio
      - USE_HTTPS=True
      - TZ=Europe/Paris
      - ZILEAN_ENABLED=false
    volumes:
      - ./data/stream-fusion:/app/config
    depends_on:
      - stremio-postgres
      - stremio-redis

  stremio-redis:
    image: redis:latest
    container_name: stremio-redis
    restart: unless-stopped
    volumes:
      - ./data/stremio-redis:/data
    command: redis-server --appendonly yes

  stremio-postgres:
    image: postgres:16.3-alpine3.20
    container_name: stremio-postgres
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=stremio
      - POSTGRES_PASSWORD=stremio
      - POSTGRES_DB=zilean
    volumes:
      - ./data/stremio-postgres:/var/lib/postgresql/data/pgdata
